language: php

php:
  - 5.4
  - 5.5

before_script:
    - sudo composer self-update
    - composer install

script: phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
